[build-system]
requires = [
    "setuptools>=42.0.0",
    "setuptools_scm[toml]>=3.4",
    "packaging"
]

build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "src/legend_optics/_version.py"
